# Experiment No 12
# Name:Atharva Jadhav
## PRN:25070123027
### Topic: To perform Preprocessing on a Dataset and Dealing with Missing values
### Batch:ENTC A2

In [22]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1':[11,21,np.nan],'C2':[15,np.nan,np.nan],'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [16]:
# Boolen Function
df1.isna()

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [17]:
# Inverter to Boolean Function
df1.notna()

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [18]:
# Coloumn wise na Values
df1.isna().sum()

C1    1
C2    2
C3    0
dtype: int64

In [19]:
# NAN Rows are Dropped (Checked Horizontally)
df1=df1.dropna()
df1

     C1    C2  C3
0  11.0  15.0  10

In [23]:
df1.fillna(value='DEFAULT')

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [24]:
# Mean Values of Coloumns are Calculated
df1.fillna(value=df1.mean())

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [26]:
# DataSet 1
data={
    "Roll No":[101,102,103,104,105],
    "Name":["Atharva","Bedang","Gayatri","Dhvan","Neha"],
    "Age":[20,"-",21,20,"22"],
    "Marks":[85,90,"-",88,76],
    "Department":["ENTC","CSE","RNA","Mech","AIML"],
    "Admission Date":["01-06-2023","03-06-2023","05-06-2023","07-06-2023","10-06-2023"]
}
df=pd.DataFrame(data)
    # Save as CSV
df.to_csv("data.csv",index=False)
df

   Roll No     Name Age Marks Department Admission Date
0      101  Atharva  20    85       ENTC     01-06-2023
1      102   Bedang   -    90        CSE     03-06-2023
2      103  Gayatri  21     -        RNA     05-06-2023
3      104    Dhvan  20    88       Mech     07-06-2023
4      105     Neha  22    76       AIML     10-06-2023

In [27]:
# Step 2 Replace '-' with NAN to mark missing Values
df.replace("-",np.nan,inplace=True)
df

/tmp/ipykernel_514/3536561995.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-",np.nan,inplace=True)

   Roll No     Name  Age  Marks Department Admission Date
0      101  Atharva   20   85.0       ENTC     01-06-2023
1      102   Bedang  NaN   90.0        CSE     03-06-2023
2      103  Gayatri   21    NaN        RNA     05-06-2023
3      104    Dhvan   20   88.0       Mech     07-06-2023
4      105     Neha   22   76.0       AIML     10-06-2023

In [28]:
# Convert Coloumns to Numeric where Needed
df["Age"]=pd.to_numeric(df["Age"],errors='coerce')
df["Marks"]=pd.to_numeric(df["Marks"],errors='coerce')
df

   Roll No     Name   Age  Marks Department Admission Date
0      101  Atharva  20.0   85.0       ENTC     01-06-2023
1      102   Bedang   NaN   90.0        CSE     03-06-2023
2      103  Gayatri  21.0    NaN        RNA     05-06-2023
3      104    Dhvan  20.0   88.0       Mech     07-06-2023
4      105     Neha  22.0   76.0       AIML     10-06-2023

In [29]:
# Check Missing Values
print("\nMissing Values\n")
print(df.isnull().sum())

Missing Values

Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission Date    0
dtype: int64

In [30]:
# Fill missing age with mean
df["Age"].fillna(df["Age"].mean(),inplace=True)
df

/tmp/ipykernel_514/2135787989.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

   Roll No     Name    Age  Marks Department Admission Date
0      101  Atharva  20.00   85.0       ENTC     01-06-2023
1      102   Bedang  20.75   90.0        CSE     03-06-2023
2      103  Gayatri  21.00    NaN        RNA     05-06-2023
3      104    Dhvan  20.00   88.0       Mech     07-06-2023
4      105     Neha  22.00   76.0       AIML     10-06-2023

In [31]:
# Median for Marks
df["Marks"].fillna(df["Marks"].median(),inplace=True)
df

/tmp/ipykernel_514/1744195843.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(),inplace=True)

   Roll No     Name    Age  Marks Department Admission Date
0      101  Atharva  20.00   85.0       ENTC     01-06-2023
1      102   Bedang  20.75   90.0        CSE     03-06-2023
2      103  Gayatri  21.00   86.5        RNA     05-06-2023
3      104    Dhvan  20.00   88.0       Mech     07-06-2023
4      105     Neha  22.00   76.0       AIML     10-06-2023

In [32]:
print(df.isnull().sum())

Roll No           0
Name              0
Age               0
Marks             0
Department        0
Admission Date    0
dtype: int64

In [34]:
# Step 5: Fix inconsistent text fromatting
df["Department"]=df["Department"].str.upper()
df

   Roll No     Name    Age  Marks Department Admission Date
0      101  Atharva  20.00   85.0       ENTC     01-06-2023
1      102   Bedang  20.75   90.0        CSE     03-06-2023
2      103  Gayatri  21.00   86.5        RNA     05-06-2023
3      104    Dhvan  20.00   88.0       MECH     07-06-2023
4      105     Neha  22.00   76.0       AIML     10-06-2023

In [35]:
# Step 6: Convert Admission Date to standard date format
df["Admission Date"]=pd.to_datetime(df["Admission Date"])
df

   Roll No     Name    Age  Marks Department Admission Date
0      101  Atharva  20.00   85.0       ENTC     2023-01-06
1      102   Bedang  20.75   90.0        CSE     2023-03-06
2      103  Gayatri  21.00   86.5        RNA     2023-05-06
3      104    Dhvan  20.00   88.0       MECH     2023-07-06
4      105     Neha  22.00   76.0       AIML     2023-10-06

In [37]:
# Step 7 Save Cleaned data
df.to_csv("cleaned_student_data.csv",index=False)
print("Cleaned data saved to cleaned_student_data.csv")

Cleaned data saved to cleaned_student_data.csv

In [43]:
# Upload the Dataset 2
import pandas as pd
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

# Checking for missing values

In [45]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

# Imputing the missing value

In [46]:
#1.Luggage Room
df['Luggage.room']=df['Luggage.room'].fillna(df['Luggage.room'].mean())
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [47]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room       0
dtype: int64

In [48]:
#2.Rear Seat Room
df['Rear.seat.room']=df['Rear.seat.room'].fillna(df['Rear.seat.room'].mean())
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [49]:
# Airbags
df['AirBags']=df['AirBags'].fillna(df['AirBags'].mode().values[0])
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver only,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,Driver only,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,Driver only,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [50]:
# Save Cleaned DataSheet
df.to_csv("cleaned_Cars93.csv",index=False)